### PR TITLE
WIP: Add links to SUSE Manager and SUSE Manager for Retail

### PR DESCRIPTION
**Pull request by juliogonzalez**
Ping @jcayouette, @Loquacity and @keichwa for awareness.

### CODE REVIEW

**Comment by sknorr** [comment]
Editing index.html directly will only bring you grief -- this file is auto-generated from inx-config.xml.

How about adding the SUMA link to the end of the \<desc\> tag? https://github.com/SUSEdoc/susedoc.github.io/blob/master/index-config.xml#L10

**Comment by juliogonzalez** [comment]
Yikes! This is a RTFM just in my face (my fault for not reading the really simple `README.md`!) :-D

Anyway I am thinking about closing the PR, as it seems we don't have autogenerated doc yet for the GitHub branches (I thought the link I added was automatically updated, but no... doc team is still working on it)

@Loquacity what's your opinion? When can we expect to have automatically generated doc from the branches?

**Comment by Loquacity** [comment]
> @Loquacity what's your opinion? When can we expect to have automatically generated doc from the branches?

We're getting closer. We've got a branch called /beta1 now which has the draft docs (including lovely watermarks, etc), which yesterday was working here: https://suma-refhead-srv.mgr.suse.de/docs/suse-manager/beta1/release-notes-version-4.0.html

@jcayouette can you please provide the correct beta1 URL to @juliogonzalez ?

**Comment by sknorr** [comment]
I'll close this, as we have that mention in the `<desc/>` now.

**Pull request closed without merging**
